#ifndef COURSE_METADATA_H
#define COURSE_METADATA_H

/*
 * Runtime access to course_metadata.bin, the fixed big-endian form of
 * the ROM course table generated by tools/rom_assets.py. It carries the
 * per-course values load_course needs; the previous port compiled stale
 * copies of these into the binary (packoffs[], gCourseTable.vertexCount).
 */

#include <stddef.h>
#include <stdint.h>

#define COURSE_METADATA_COURSES 20

struct CourseMetadata {
    uint32_t vertexCount;             /* CourseVtx records in the vertex mio0 */
    uint32_t packedOffset;            /* start of packed displaylists in _geography.bin */
    uint32_t finalDisplaylistOffset;  /* unpacked displaylist byte span */
    uint32_t unknown1;                /* course table word 11 (high half) */
};

/*
 * Parse a course_metadata.bin blob into out[0..max_courses). Returns the
 * course count on success, -1 on any malformed input (magic, version,
 * truncation, or more courses than the caller can hold).
 */
int course_metadata_parse(const void* blob, size_t size,
                          struct CourseMetadata* out, size_t max_courses);

/* Read and parse the course_metadata.bin asset; fails via platform_fatal. */
void course_metadata_load(void);

/* Metadata for one course; fails via platform_fatal when unloaded or out
 * of range. */
const struct CourseMetadata* course_metadata_get(int courseId);

#endif /* COURSE_METADATA_H */
